### ISSUE TITLE
Which Token Permissions Do I Need to Acquire?

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/mergem#26]
I run the scheduled job from the forked "mergem"  repository and got the next exception: 
```sh
E: Octokit::Forbidden: POST https://api.github.com/repos/volodya-lombrozo/jtcop/issues/290/comments: 403 - Resource not accessible by personal access token // See: https://docs.github.com/rest/issues/comments#create-an-issue-comment
```
As I understand it, my token has incorrect permissions. Which specific rights should I obtain? I aim to acquire the token with the minimal required set of permissions for security reasons.

**Comment by volodya-lombrozo** [comment]
Here is failed job: https://github.com/volodya-lombrozo/mergem/actions/runs/6781554775/job/18432070942#step:6:21
PS: I believe it would be great to have this info in README

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by yegor256** [comment]
@volodya-lombrozo this is what I have:

<img width="871" alt="Screenshot 2023-11-07 at 11 19 33" src="https://github.com/yegor256/mergem/assets/526301/c12f7c92-abc5-49ee-a7f2-3b3b9be334d7">

Feel free to submit a PR to update REAMDE
